spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/alien_db
    username: alien
    password: alien
    driver-class-name: org.postgresql.Driver
#    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
      platform: postgres
server:
  port: 8084

